# Generated by Django 4.1.7 on 2023-04-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0003_rename_distributeitem_removeitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ManyToManyField(
                blank=True, related_name="items", to="stock.category"
            ),
        ),
    ]
