# Generated by Django 4.1.7 on 2023-04-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0005_alter_item_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="price",
        ),
        migrations.RemoveField(
            model_name="item",
            name="quantity",
        ),
        migrations.AddField(
            model_name="receiveitem",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="receiveitem",
            name="quantity",
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name="removeitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="removeitem",
            name="quantity",
            field=models.IntegerField(default=1, null=True),
        ),
    ]
