# Generated by Django 4.1.7 on 2023-04-11 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0006_remove_item_price_remove_item_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receiveitem",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="removeitem",
            name="quantity",
        ),
    ]
