# Generated by Django 4.1.7 on 2023-04-11 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0007_remove_receiveitem_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiveitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_items",
                to="stock.item",
            ),
        ),
        migrations.AlterField(
            model_name="removeitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="removed_items",
                to="stock.item",
            ),
        ),
    ]
