# Generated by Django 4.1.7 on 2023-04-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0011_changeitem_delete_updateitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="changeitem",
            name="count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
