# Generated by Django 4.1.7 on 2023-04-11 19:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0012_changeitem_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="changeitem",
            options={"ordering": ("-created_at",)},
        ),
    ]
