# Generated by Django 4.1.7 on 2023-04-13 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0003_unitsection_employee_unit"),
        ("stock", "0013_alter_changeitem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="changeitem",
            name="dept",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employees.department",
            ),
        ),
        migrations.AddField(
            model_name="changeitem",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="changeitem",
            name="unit_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employees.unitsection",
            ),
        ),
    ]
