# Generated by Django 4.1.7 on 2023-04-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0015_alter_changeitem_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="init_count",
            field=models.IntegerField(default=1, verbose_name="quantity"),
        ),
    ]
