# Generated by Django 4.1.7 on 2023-04-19 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0018_item_qty_alter_item_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="qty",
        ),
    ]
