# Generated by Django 4.1.7 on 2023-04-25 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0019_remove_item_qty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="changeitem",
            old_name="dept",
            new_name="section",
        ),
        migrations.RemoveField(
            model_name="changeitem",
            name="unit_section",
        ),
    ]
