# Generated by Django 4.1.7 on 2023-04-24 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_allownewusers"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AllowNewUsers",
            new_name="AllowNewUser",
        ),
    ]
