# Generated by Django 4.1.7 on 2023-04-24 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_allownewusers_allownewuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AllowNewUser",
        ),
    ]
