# Generated by Django 4.1.7 on 2023-04-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computerassignment",
            name="date_assigned",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="computerassignment",
            name="date_returned",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
