# Generated by Django 4.1.7 on 2023-04-13 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0003_itemassignment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ItemAssignment",
        ),
    ]
