# Generated by Django 4.1.7 on 2023-04-25 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0008_alter_printerassignment_dept_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="computerassignment",
            old_name="dept",
            new_name="section",
        ),
        migrations.RenameField(
            model_name="printerassignment",
            old_name="dept",
            new_name="section",
        ),
        migrations.RenameField(
            model_name="scannerassignment",
            old_name="dept",
            new_name="section",
        ),
        migrations.RemoveField(
            model_name="computerassignment",
            name="unit_section",
        ),
        migrations.RemoveField(
            model_name="printerassignment",
            name="unit_section",
        ),
        migrations.RemoveField(
            model_name="scannerassignment",
            name="unit_section",
        ),
    ]
