# Generated by Django 4.1.7 on 2023-04-26 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0008_alter_printer_supplier"),
        ("assignments", "0009_rename_dept_computerassignment_section_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printerassignment",
            name="printer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="c",
                to="equipment.printer",
            ),
        ),
    ]
