# Generated by Django 4.1.7 on 2023-04-26 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0004_rename_department_section_remove_employee_dept_and_more"),
        ("assignments", "0011_alter_printerassignment_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printerassignment",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_printers",
                to="employees.employee",
            ),
        ),
        migrations.AlterField(
            model_name="printerassignment",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="section_printers",
                to="employees.section",
            ),
        ),
    ]
