# Generated by Django 4.1.7 on 2023-04-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0014_alter_printerassignment_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="computerassignment",
            name="is_assigned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="printerassignment",
            name="is_assigned",
            field=models.BooleanField(default=False),
        ),
    ]
