# Generated by Django 4.1.7 on 2023-04-26 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0015_computerassignment_is_assigned_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="printerassignment",
            unique_together=set(),
        ),
    ]
