# Generated by Django 4.1.7 on 2023-04-26 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0018_alter_computerassignment_date_assigned_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computerassignment",
            name="date_assigned",
            field=models.DateField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="computerassignment",
            name="date_returned",
            field=models.DateField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
