# Generated by Django 4.1.7 on 2023-04-26 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0004_rename_department_section_remove_employee_dept_and_more"),
        ("assignments", "0020_alter_computerassignment_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computerassignment",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_computers",
                to="employees.employee",
            ),
        ),
    ]
