# Generated by Django 4.1.7 on 2023-04-26 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0022_alter_computerassignment_date_assigned_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="computerassignment",
            options={"ordering": ["-pk"]},
        ),
        migrations.AlterModelOptions(
            name="printerassignment",
            options={"ordering": ["-pk"]},
        ),
    ]
