# Generated by Django 4.1.7 on 2023-05-15 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0023_alter_computerassignment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="computerassignment",
            options={},
        ),
    ]
