# Generated by Django 4.1.7 on 2023-05-15 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0024_alter_computerassignment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="printerassignment",
            options={},
        ),
    ]
