# Generated by Django 4.1.7 on 2023-05-15 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0025_alter_printerassignment_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="computerassignment",
            name="is_assigned",
        ),
        migrations.RemoveField(
            model_name="printerassignment",
            name="is_assigned",
        ),
    ]
