# Generated by Django 4.1.7 on 2023-04-07 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0001_initial"),
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.AddField(
            model_name="computer",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="computers",
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="printer",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="scanner",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="suppliers.supplier",
            ),
        ),
    ]
