# Generated by Django 4.1.7 on 2023-04-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "equipment",
            "0002_delete_category_computer_supplier_printer_supplier_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="computermodel",
            name="memory",
            field=models.CharField(blank=True, default="8", max_length=255),
        ),
        migrations.AlterField(
            model_name="computermodel",
            name="processor",
            field=models.CharField(blank=True, default="i5", max_length=255),
        ),
        migrations.AlterField(
            model_name="computermodel",
            name="storage",
            field=models.CharField(blank=True, default="500", max_length=255),
        ),
        migrations.AlterField(
            model_name="printermodel",
            name="colour_printer",
            field=models.BooleanField(default=False),
        ),
    ]
