# Generated by Django 4.1.7 on 2023-04-26 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0001_initial"),
        ("equipment", "0008_alter_printer_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computer",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="computers",
                to="suppliers.supplier",
            ),
        ),
    ]
