# Generated by Django 4.1.7 on 2023-04-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0020_rename_dept_changeitem_section_and_more"),
        ("equipment", "0009_alter_computer_supplier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="printermodel",
            name="ink",
        ),
        migrations.AddField(
            model_name="printermodel",
            name="ink",
            field=models.ManyToManyField(to="stock.item"),
        ),
    ]
